name: "verify" 
on:
  pull_request:
  push:
    paths-ignore:
      - ".github/**"
permissions: {}
jobs:
  prettier:
    name: "check formating"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - run: npm ci
      - run: npx prettier --check .
  eslint:
    name: "check linting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - run: npm ci
      - run: npx eslint
  tsc:
    name: "check building"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - run: npm ci
      - run: npx tsc
